before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
language: java

script: "mvn deploy --settings target/travis/settings.xml"

branches:
  except:
    - travis

env:
  global:
    secure: "nNbFIeIDRiy7gN6Vn6sq2HiFzASvQTb5gparLXwNvbv662SbauAmck8lV2i2pcE6i8OnXuuBD5ZXFA1ouaogsx6IWlkTu2VTwSn4/Zh1AMlEf2ETeo9EfuYdjKNPm+exXwyltEmhDROgR7zVgxQKtrB3Gno5C8VBYdC67vhM97D2dmQN6hJGzgz5/Hu1iN6okn68flyu91KQwMAb6VheMgBGeGdPI5vQAHYq+6BOdE9uOvSqt3dsqU7y3R8fi/L9mgcUGqg9V4ocFENCE3gNq4oyMr2duqc/JcrSn4eMYFBH0Bq/OcnP2Wac9D0Gs8dNmmQopfRXT0kx3bnojBxGtsrcPVG6Cvi6xNlvHyLQRzLowB/Hn+jHzySGDkz+Vm8I3iDC1YRI0sAl6ObEV8z5HKlFmIZW++//zwhKf2e/waclDpTBnmUsScx+oUvnju0AQzRM+8LpvmSuqyaD2falinbHgEpj8s2w2vyEvSbQ8fhtGdKhMDoFgnS5b1b021oqytJh68FkD7UEMFWQIpLNn1iFruMcKh8oBtpgZcmEFISSwoLJXaczBQbKQWBgvxCFXYuCaugzI/rL/V7KZXFq1ud1Na6BOmoJV8zl+4gCo9txq3e2NRH9Ar2QZBYDMXxgDoes0RLGsmfQFFvp0v7SBg2lg8y0/PGVSt5jBNg5Ed0="
    secure: "lrmw5w5Uh3xjsbK0maKvg+iiLZmSP9AjgG+qYYlw21vSvWwP97mgc4nijjQfRSFH/giernNBAyrgzYJNG9YipnJ+54Vp2dvJZr/5u6KCS6taNWvsgUDYTVt+PmcxDLwlXcGsiqey+NMFa13rf3aMKgmEeh984qvzkNjyUTfKWeWUH7kDElXuU7w+Of8qqMpKJJv+ZyUhjp/YdO/JcHEQHPUtSD9lEL8PzStHi7M5zXKCc74NRzzjlv2X5WuFpdhM7OigBbjqggCcP5g69UM2PHeBM0rb2lCHHMi5lVy5QdOoq4uweuNMVO8cJX5Izxa2fGeqvWHLAYB3KfhXL1pN/V1ogqFqi6+LG9tth/OVgBdwSg1RzNdedcM2sf3uIYXmwFo6EqVRNJNAGB0SYmk8AXLmk154AWbArvWx8Kh73WdDDneRTUfZGSVilHEJTY2VS6FJ2k/NWWPF8yvhInmGpFRZElaI4w+ingOC6LPrYBazvyBjrVeJHm2wd+0osqN6ef2qdvdfpIhUs2uWc4ZoZtgnDIEODMXLtOMxmCTTpqQWbpZk2Xktvrr/QULm1QDUpM0WxFahtxJbrtW1G4YLD2mUTthpmnxfTddVBAzIYl5tz4g0yJmvVvO7f41MKvcFnltRvnyyCTUPDFadz68V9SSU0dr6hR/0oUjREWMvDas="
