before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
language: java

script: "mvn deploy --settings target/travis/settings.xml"

branches:
  except:
    - travis

env:
  global:
  - secure: vI9eCyhdPA0NwdrMOJsq1sUGkuIYdKyQam/LEsn+STl3M/CkfgJNq5zlluaE5EqTN8B5uDPV+4YOL0Izb6/V+4rvhdw8/dOtNfiU8KvOQtgVoNj7hf02vgoZk90Q166I2StDElQ3RG48wJUptZM0ajhIsP/oWzjlksvBJJSsPImeaGKntwnkHAez674YuzEu/R9jK2urumsfyf/8aeYHl+zX0NmGBeCiNZT4/1/ozzGnv1feGI26w+rtxfYKVvLe8m/zCQQnRlVOdO28eRW+nAq62W8rF8jQ/2+HDTnPrhdgJwZU/T6Bbg3Q285rc5iScA5n/4ePfNrOJesPgrz7uMM7bui4qBEhgEfQdimKzzlUUFeeE4/h5vpnAnQQxMs5OX8Q2ePzPwA18xgLeC4sd83qFFWJTbQUXwdqWdTLD7NpSo9QoDoWBLHl5NK96E+CdRjXv39/+rCXnmgP/ibQu9UBHNmrKGgQO1GODhsPPtxy0xNFeIMypojkTbUGPs4AxHNGpTkAVma3sAJXfm/zZQrvcwM0qnMrH6EM6HqpFwisyw0OkWNxPbcHP95zKNfHJpX92XVFCarcY3e8ao5Fr7tbjx9cpa1TPDM7mDIQUbpkGKFK4mmIKgg5BphFrz4kMPSi4tSZ0M99jYdYMW76FiVbg9i25midemoP/9vWpO8=
  - secure: AffwHZmcxATjBZfjW2EAR1ZXpUj0vwrDpLWpj8FF5qMoacLZ0+kxSKQFBy81swjldWUMo+A7kqmVqTe31M9qhQIUE77tPy2FCSj+3m8ioAnfv3y2F5Bq+Uk5raT7O+YU5wCM0hdePkLjAD0vhgl5fI8eYC3MgdlIyKdof7BnstriGEsoaW0VFsghQbpxLF+HQdLkhPd6XdTjMPljoqfEaoxpOIWJS21YjhJAqAROlEiqu2JtZ6pXRN7V32jIb4yEhvtwDnykdpIgKs6gdx4tyZ2YInb2fMKhjCxhyrRT7wKfpdUgIk0eelUeKJesFZ+uFvTve6Bt1OZ0RPm+SUQql4kM2/3te+Bl4Tj+uzYEAxW7tz5I3gVrc2kUtSmYErx1ff5orfB5TU2dkcGB9jipB692BfMldhws4fnlmFT8UX/aqPyJCYF9lGaXubf81LNn6wr2YzPDzEvc+SraVx2p/05cZNNl+58hK0Mc0oprotMiFI2L7NVH9pf4maNQGzP55q03onYvEys8kBeqofoF6Yt+JzJifUDYUDdUO9j5UlwlLmCBbofX5zp2OMq9u8MqaPcF8CX/87I3tWV06rUhmn26MoWlViAd6fDg5a/jXnlO7zYaFjHREOWO9cdCV+bV+I6jgVggXfGVeXkhf1oWPfJDOWYJQyjcHcVTX7DZkrM=

