before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
language: java

script: "mvn deploy --settings target/travis/settings.xml"

branches:
  except:
    - travis

env:
  global:
    secure: "C3WxJeSSIJA5bWMkeTbXt7u187Byo9/wtFdFxbRDyp6KN5POmEY2ATS/4r81CqsjvXpj7IGC5xKaJcjXpDZdLnsvIggnvCkX+rsMvbcMdiU7xkzHOCc4A/Wz606eTZVt/bmYdPzWErE6o1jxqm7+iqZkop1z0MDEM+VbqhO+piS9jmvPe7dsCYoBOtcroHP05+fVKCFLUj3rLd1FgITIXM6WD8gCqXIjTm88EMkQOKAYBFDnXfbdHhkafpp7NjgfKk/sMKVd5Ds6u+uj8yxs5wNv/HbySttgUPaMdtnLdm5urgNo6dUFShLaPFVLnbDX34djcoXwijYLSQgazAp7IW4gf1NnT2Ix4GXL2xFlnrtHbcqeupsCisuPArdMKYSvtexmMrKYkF2X22T0VEmBBZm6TSFLbTVfB1q60CJ2AUvwop43Nb6cYGTiPXih4XJN1Uoi+iWt/PqN7YddiWSej2h5VU8ySLP8lBFh/11fqsjXOF5PKqAgaw8YTKtp558mtbUjzBrm5eBIrToIhx3YNU8cOlwahQ/xukG3jayzrxAuKYCabhEnEurH0qZYuucZkpzMtgqCaUdCvbpbdPfEqPmy4meY+lqiikA8vHhYgymRE+XUBXd4yUaZCNFJ5EJE8vFEbxJKo4i2tawme3AHKyzuq/QGD/go354OlmgHXeU="
    secure: "wtdq5ROrrg+QroLCBZVMzkVySiKKiXTYDMz4SkLBvKt8hKcVWor3VhI+Ks/zcz30MPaVaMWbzL7SlEFgmb8NCYL7dFKI9lcUaGJ4hEqupJwrpcHRDae5zQ5cgA/0dzRptsqUqFMTEhtEf38m+plA13NE+SzvJEadGB1xVLRKDfU23JYhXbDaJukpn1CyWoy+CZ2i6xpWuEZ0Lj1X9o2s64Q2Cw2cECtfC9a33yjsXsNUNlri1m5Pvrc9Te1wJc5Eqm+UQs9V+akfgFo94sNsrLopyz8xjTgptHy14FQiNsfIaU3XaP2SxsIrAw00izIh0eRkOjWXM7LpqSl6d4XNSV4qHMqfurQErseEUmj91SWdhwCseP5ZQQsKXMigaOqLVEdSttR7vpsDUUxIAC6xH9lohEgTn+FabGzZsBK8s2E6bmEdYBxaHdJ4aLsuq3YOxcsqEhLu7xcvjqXTYbtSvzySM1ehYvLHlZdHj6eEoFk0CsAAC1soP0HxLP4vsVxwgp/0AvX6v6Lutzb4gMCbnxPP9l/TzjgFkgmk1E2weWcW0dxNkpkrdxB3nBEDoDlKorXLeY5mxNZWQT74XZNbflLu5EwUTNPm529cLUf17AEH2yG0LghcSasS522QJ6sUACXUJtkgS+SYy6Zdxk3JBEeUAnKiojOazevWMpp/jj4="

